# NumPy - Numerical Computing Essentials

**What is this file?**  
Foundation library for numerical operations — arrays, matrices, and mathematical functions.

---

## 📚 Contents

| # | Topic | Key Concepts |
|---|-------|--------------|
| 1 | Basics | Array creation, shape, dtype |
| 2 | Indexing | Slicing, accessing elements |
| 3 | Initialization | `zeros()`, `ones()`, `random()` |
| 4 | Math Operations | Arithmetic, broadcasting |
| 5 | Linear Algebra | Matrix multiplication, `dot()` |
| 6 | Statistics | Mean, std, min, max |
| 7 | Reshaping | `reshape()`, transpose, flatten |
| 8 | File I/O | `genfromtxt()` for CSV |
| 9 | Boolean Masking | Conditional filtering |
| 10 | Normalization | Statistical concepts |

## Section 1: Import NumPy Library
**Import the NumPy library and initialize it for use**

In [4]:
import numpy as np

## Section 2: The Basics - Creating and Understanding Arrays
**Learn how to create NumPy arrays and understand their properties**

In [5]:
# Creating a basic NumPy array with integer data type
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
# Check the type of NumPy array object
type(a)

numpy.ndarray

In [7]:
# Reshape a 1D array into 2D (1 row, 3 columns)
a.reshape(1,3)

array([[1, 2, 3]], dtype=int32)

In [8]:
# Create a 2D array (2x3 matrix) with float values
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get the number of dimensions of the array
a.ndim

1

In [10]:
# Get the shape (dimensions) of the array
b.shape

(2, 3)

In [11]:
# Get the data type of array elements
a.dtype

dtype('int32')

In [12]:
# Get the size (in bytes) of each array element
a.itemsize

4

In [13]:
# Get the total size (in bytes) of the array
a.nbytes

12

In [14]:
# Get the total number of elements in the array
a.size

3

## Section 3: Accessing and Changing Elements
**Index, slice, and modify specific elements, rows, and columns in arrays**

In [65]:
# Create a 2D array for indexing examples
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Access a specific element at row 1, column 5
a[1, 5]

np.int64(13)

In [17]:
# Access an entire row (row 0) and all column 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Access an entire column (column 2)
a[:, 2]

array([ 3, 10])

In [ ]:
# Slice with step size: [start:end:step]
a[0, 1:-1:2]
a[:,3:5:1] # Last one will not count 

array([[ 4,  5],
       [11, 12]])

In [66]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [67]:
# Modify specific elements and entire columns
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### Working with 3D Arrays
**Examples of indexing and modifying 3D arrays**

In [69]:
# Create a 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [70]:
b.shape

(2, 2, 2)

In [71]:
b.ndim

3

In [22]:
# Access element in 3D array [matrix, row, column]
b[0,1,1]

np.int64(4)

In [23]:
# Modify a column in the 3D array
b[:, 1] = [9, 8]

In [24]:
# Display the modified 3D array
b

array([[[1, 2],
        [9, 8]],

       [[5, 6],
        [9, 8]]])

## Section 4: Initializing Different Types of Arrays
**Create arrays with specific patterns and values**

In [25]:
# Create an array filled with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Create an array filled with ones
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [73]:
# Create an array filled with a specific value (99)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [75]:
# Create an array with same shape as 'a', filled with value 4
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Generate random decimal numbers between 0 and 1
np.random.rand(4,2)

array([[0.05342401, 0.01975613],
       [0.07304993, 0.26763556],
       [0.80441541, 0.84323329],
       [0.74336035, 0.23886671]])

In [30]:
# Generate random integers between -4 and 8
np.random.randint(-4,8, size=(3,3))

array([[ 0, -2,  2],
       [ 0, -2,  7],
       [-4,  3,  3]], dtype=int32)

In [31]:
# Create an identity matrix (1s on diagonal, 0s elsewhere)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# Repeat array elements along an axis
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
# Create complex array patterns by combining arrays
output = np.ones((5,5))
print("Original 5x5 array:")
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print("\n3x3 array with center value = 9:")
print(z)

# Insert the 3x3 array into the center of the 5x5 array
output[1:-1,1:-1] = z
print("\nFinal combined array:")
print(output)

Original 5x5 array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

3x3 array with center value = 9:
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

Final combined array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Important: Array Copying
**Understanding array references vs. copies**

In [34]:
# Use .copy() to create an independent copy of an array
a = np.array([1,2,3])
b = a.copy()  # Create a true copy
b[0] = 100    # Modifying b doesn't affect a
print("Original array a:", a)
print("Copied and modified array b:", b)

Original array a: [1 2 3]
Copied and modified array b: [100   2   3]


## Section 5: Mathematics - Arithmetic Operations
**Perform arithmetic operations on array elements**

In [35]:
# Create array for arithmetic operations
a = np.array([1,2,3,4])
print("Original array:", a)

Original array: [1 2 3 4]


In [36]:
# Addition - add 2 to each element
a + 2

array([3, 4, 5, 6])

In [37]:
# Subtraction - subtract 2 from each element
a - 2

array([-1,  0,  1,  2])

In [38]:
# Multiplication - multiply each element by 2
a * 2

array([2, 4, 6, 8])

In [39]:
# Division - divide each element by 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
# Element-wise operations between two arrays
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [41]:
# Power - raise each element to the power of 2
a ** 2

array([ 1,  4,  9, 16])

In [42]:
# Trigonometric function - cosine of each element
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Section 6: Linear Algebra - Matrix Operations
**Matrix multiplication and linear algebra operations**

In [83]:
# Create two matrices for linear algebra operations
a = np.ones((2,3))
b = np.full((3,2), 2)
print("Matrix a (2x3):")
print(a)
print("\nMatrix b (3x2):")
print(b)

Matrix a (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Matrix b (3x2):
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# Matrix multiplication using dot product
result = np.dot(a, b)
print("Matrix product (a @ b):")
print(result)

Matrix product (a @ b): [[6. 6.]
 [6. 6.]]


In [ ]:
# Alternative way to do matrix multiplication dot product
result2 = a @ b
print("Using @ operator for matrix multiplication:")
print(result2)

Using @ operator for matrix multiplication:
[[6. 6.]
 [6. 6.]]


## Section 7: Statistics - Descriptive Analysis
**Calculate statistical measures on array data**

In [46]:
# Create array for statistical calculations
stats_arr = np.array([1,2,3,4,5])
print("Array for statistics:", stats_arr)

Array for statistics: [1 2 3 4 5]


In [47]:
# Calculate mean (average) of array elements
mean_val = np.mean(stats_arr)
print("Mean:", mean_val)

Mean: 3.0


In [48]:
# Calculate variance and standard deviation
var_val = np.var(stats_arr)
print("Variance:", var_val)

Variance: 2.0


In [49]:
# Calculate min and max values in the array
min_val = np.min(stats_arr)
max_val = np.max(stats_arr)
print("Minimum:", min_val, "Maximum:", max_val)

Minimum: 1 Maximum: 5


## Section 8: Reorganizing Arrays - Reshaping and Transposing
**Change array structure and orientation**

In [50]:
# Create array for reshaping demonstrations
arr = np.arange(1, 7)  # Create [1,2,3,4,5,6]
print("Original 1D array:", arr)

Original 1D array: [1 2 3 4 5 6]


In [ ]:
# Reshape creates 1D array into 2D array (2 rows x 3 columns)
reshaped = arr.reshape(2, 3)
print("Reshaped to (2,3):")
print(reshaped)

Reshaped to (2,3):
[[1 2 3]
 [4 5 6]]


In [52]:
# Transpose a matrix (swap rows and columns)
transposed = reshaped.T
print("Transposed (3,2):")
print(transposed)

Transposed (3,2):
[[1 4]
 [2 5]
 [3 6]]


## Section 9: Data Loading - Reading from Files
**Load data from CSV files using NumPy**

## Section 10: Boolean Masking - Filtering Data
**Use conditions to filter and extract array elements**

In [53]:
# Create array for boolean masking and apply filter conditions
mask_arr = np.array([1,2,3,4,5,6,7,8,9,10])
mask = (mask_arr > 3) & (mask_arr < 8)
filtered = mask_arr[mask]
print("Elements between 3 and 8:", filtered)

Elements between 3 and 8: [4 5 6 7]


In [54]:
# Create unsorted array for sorting demonstration
sort_arr = np.array([3,1,4,1,5,9,2,6])
print("Original unsorted array:", sort_arr)

Original unsorted array: [3 1 4 1 5 9 2 6]


In [91]:
# Sort array in ascending order and find indices where condition is true
sorted_arr = np.sort(sort_arr)
print("Sorted array:", sorted_arr)

# Find indices of elements greater than 4
indices = np.where(sorted_arr > 4)
print("Indices where elements > 4:", indices)
print("Elements at those indices:", sorted_arr[indices[0]])

Sorted array: [1 1 2 3 4 5 6 9]
Indices where elements > 4: (array([5, 6, 7]),)
Elements at those indices: [5 6 9]


In [92]:
# Concatenate multiple arrays
concat_result = np.concatenate([sorted_arr, [10, 11, 12]])
print("Concatenated array:", concat_result)

Concatenated array: [ 1  1  2  3  4  5  6  9 10 11 12]


# Section 11: Statistical concept-Normalization


In [57]:
Data = np.array([1,2,3,4])

# Mean
mean = np.mean(Data)
print("mean is ", mean)

# Median
median = np.median(Data)
print("Median is ", median)

# Standard deviation
std_dev = np.std(Data)
print("mean is ", std_dev)

# Variance
variance = np.var(Data)
print("Variance is ", variance)

mean is  2.5
Median is  2.5
mean is  1.118033988749895
Variance is  1.25


In [58]:
# To have a mean of 0 and standard deviation of 1 
# Normalized Data 

Data = np.array([1,2,3,4])

mean = np.mean(Data)
std_dev = np.std(Data)

normilized_data = (Data - mean ) / std_dev
print("Normilized data :", normilized_data)

Normilized data : [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [59]:
# logical operation
Data = np.array([1,2,3,4,6])

Data[Data>5]

array([6])