# NumPy Tutorial and Comprehensive Guide

## Overview
This notebook provides a comprehensive introduction to NumPy, a fundamental library for numerical computing in Python. NumPy provides support for arrays and matrices, along with mathematical functions to operate on these data structures.

## Content Overview

### Section 1: Import NumPy Library
- Learn how to import NumPy and check its version
- Understand how to access NumPy's functions and classes

### Section 2: The Basics
- Create NumPy arrays from Python lists
- Understand array dimensions, shapes, and data types
- Learn about array size and reshaping arrays

### Section 3: Accessing and Changing Elements
- Index arrays using integer and slice notation
- Access elements in multi-dimensional arrays
- Change array values using indexing and slicing
- Understand negative indexing

### Section 4: Initializing Different Types of Arrays
- Create arrays filled with zeros (`np.zeros()`)
- Create arrays filled with ones (`np.ones()`)
- Create arrays filled with specific values (`np.full()`)
- Create identity matrices (`np.identity()`)
- Generate random numbers and integers
- Repeat array elements (`np.repeat()`)
- Create complex array patterns
- Learn about array copying and references

### Section 5: Mathematics - Arithmetic Operations
- Perform addition, subtraction, multiplication, and division on arrays
- Element-wise operations between arrays
- Power operations and trigonometric functions
- Broadcasting with scalars and arrays

### Section 6: Linear Algebra - Matrix Operations
- Create matrices for linear algebra operations
- Perform matrix multiplication using `np.dot()`
- Use the `@` operator for matrix multiplication
- Understand matrix dimensions and compatibility

### Section 7: Statistics - Descriptive Analysis
- Calculate mean (average) of array elements
- Calculate variance and standard deviation
- Find minimum and maximum values in arrays
- Understand statistical measures for data analysis

### Section 8: Reorganizing Arrays - Reshaping and Transposing
- Reshape arrays from one dimension to another
- Transpose matrices (swap rows and columns)
- Flatten multi-dimensional arrays to 1D
- Understand array structure manipulation

### Section 9: Data Loading - Reading from Files
- Load data from CSV files using `np.genfromtxt()`
- Access specific rows and columns from loaded data
- Check data shape and dimensions
- Work with real-world datasets

### Section 10: Boolean Masking - Filtering Data
- Create boolean masks for conditional filtering
- Extract elements that meet specific criteria
- Combine multiple conditions with logical operators (`&`, `|`)
- Filter data based on conditions

### Section 11: Additional NumPy Operations
- Sort arrays in ascending/descending order
- Find indices where conditions are true using `np.where()`
- Access elements at specific indices
- Concatenate multiple arrays
- Perform advanced array manipulations

### Statistical concept-Normalization
- Mean
- Median
- Mode
- Normalized data


## Section 1: Import NumPy Library
**Import the NumPy library and initialize it for use**

In [2]:
import numpy as np

## Section 2: The Basics - Creating and Understanding Arrays
**Learn how to create NumPy arrays and understand their properties**

In [3]:
# Creating a basic NumPy array with integer data type
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
# Check the type of NumPy array object
type(a)

numpy.ndarray

In [5]:
# Reshape a 1D array into 2D (1 row, 3 columns)
a.reshape(1,3)

array([[1, 2, 3]], dtype=int32)

In [6]:
# Create a 2D array (2x3 matrix) with float values
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get the number of dimensions of the array
a.ndim

1

In [8]:
# Get the shape (dimensions) of the array
b.shape

(2, 3)

In [9]:
# Get the data type of array elements
a.dtype

dtype('int32')

In [10]:
# Get the size (in bytes) of each array element
a.itemsize

4

In [11]:
# Get the total size (in bytes) of the array
a.nbytes

12

In [12]:
# Get the total number of elements in the array
a.size

3

## Section 3: Accessing and Changing Elements
**Index, slice, and modify specific elements, rows, and columns in arrays**

In [13]:
# Create a 2D array for indexing examples
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Access a specific element at row 1, column 5
a[1, 5]

np.int64(13)

In [15]:
# Access an entire row (row 0)
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Access an entire column (column 2)
a[:, 2]

array([ 3, 10])

In [17]:
# Slice with step size: [start:end:step]
a[0, 1:-1:2]

array([2, 4, 6])

In [18]:
# Modify specific elements and entire columns
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### Working with 3D Arrays
**Examples of indexing and modifying 3D arrays**

In [19]:
# Create a 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Access element in 3D array [matrix, row, column]
b[0,1,1]

np.int64(4)

In [21]:
# Modify a column in the 3D array
b[:, 1] = [9, 8]

In [22]:
# Display the modified 3D array
b

array([[[1, 2],
        [9, 8]],

       [[5, 6],
        [9, 8]]])

## Section 4: Initializing Different Types of Arrays
**Create arrays with specific patterns and values**

In [23]:
# Create an array filled with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Create an array filled with ones
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Create an array filled with a specific value (99)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
# Create an array with same shape as 'a', filled with value 4
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Generate random decimal numbers between 0 and 1
np.random.rand(4,2)

array([[0.83508391, 0.21552635],
       [0.33970221, 0.88274188],
       [0.63102009, 0.9842769 ],
       [0.52228167, 0.370045  ]])

In [28]:
# Generate random integers between -4 and 8
np.random.randint(-4,8, size=(3,3))

array([[ 4,  5,  2],
       [-2, -4,  0],
       [ 1,  3, -3]], dtype=int32)

In [29]:
# Create an identity matrix (1s on diagonal, 0s elsewhere)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repeat array elements along an axis
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
# Create complex array patterns by combining arrays
output = np.ones((5,5))
print("Original 5x5 array:")
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print("\n3x3 array with center value = 9:")
print(z)

# Insert the 3x3 array into the center of the 5x5 array
output[1:-1,1:-1] = z
print("\nFinal combined array:")
print(output)

Original 5x5 array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

3x3 array with center value = 9:
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

Final combined array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Important: Array Copying
**Understanding array references vs. copies**

In [32]:
# Use .copy() to create an independent copy of an array
a = np.array([1,2,3])
b = a.copy()  # Create a true copy
b[0] = 100    # Modifying b doesn't affect a
print("Original array a:", a)
print("Copied and modified array b:", b)

Original array a: [1 2 3]
Copied and modified array b: [100   2   3]


## Section 5: Mathematics - Arithmetic Operations
**Perform arithmetic operations on array elements**

In [33]:
# Create array for arithmetic operations
a = np.array([1,2,3,4])
print("Original array:", a)

Original array: [1 2 3 4]


In [34]:
# Addition - add 2 to each element
a + 2

array([3, 4, 5, 6])

In [35]:
# Subtraction - subtract 2 from each element
a - 2

array([-1,  0,  1,  2])

In [36]:
# Multiplication - multiply each element by 2
a * 2

array([2, 4, 6, 8])

In [37]:
# Division - divide each element by 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [38]:
# Element-wise operations between two arrays
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [39]:
# Power - raise each element to the power of 2
a ** 2

array([ 1,  4,  9, 16])

In [40]:
# Trigonometric function - cosine of each element
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Section 6: Linear Algebra - Matrix Operations
**Matrix multiplication and linear algebra operations**

In [41]:
# Create two matrices for linear algebra operations
a = np.ones((2,3))
b = np.full((3,2), 2)
print("Matrix a (2x3):")
print(a)
print("\nMatrix b (3x2):")
print(b)

Matrix a (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Matrix b (3x2):
[[2 2]
 [2 2]
 [2 2]]


In [42]:
# Matrix multiplication using dot product
result = np.dot(a, b)
print("Matrix product (a @ b):")
print(result)

Matrix product (a @ b):
[[6. 6.]
 [6. 6.]]


In [43]:
# Alternative way to do matrix multiplication
result2 = a @ b
print("Using @ operator for matrix multiplication:")
print(result2)

Using @ operator for matrix multiplication:
[[6. 6.]
 [6. 6.]]


## Section 7: Statistics - Descriptive Analysis
**Calculate statistical measures on array data**

In [44]:
# Create array for statistical calculations
stats_arr = np.array([1,2,3,4,5])
print("Array for statistics:", stats_arr)

Array for statistics: [1 2 3 4 5]


In [45]:
# Calculate mean (average) of array elements
mean_val = np.mean(stats_arr)
print("Mean:", mean_val)

Mean: 3.0


In [46]:
# Calculate variance and standard deviation
var_val = np.var(stats_arr)
print("Variance:", var_val)

Variance: 2.0


In [47]:
# Calculate min and max values in the array
min_val = np.min(stats_arr)
max_val = np.max(stats_arr)
print("Minimum:", min_val, "Maximum:", max_val)

Minimum: 1 Maximum: 5


## Section 8: Reorganizing Arrays - Reshaping and Transposing
**Change array structure and orientation**

In [48]:
# Create array for reshaping demonstrations
arr = np.arange(1, 7)  # Create [1,2,3,4,5,6]
print("Original 1D array:", arr)

Original 1D array: [1 2 3 4 5 6]


In [49]:
# Reshape 1D array into 2D array (2 rows x 3 columns)
reshaped = arr.reshape(2, 3)
print("Reshaped to (2,3):")
print(reshaped)

Reshaped to (2,3):
[[1 2 3]
 [4 5 6]]


In [50]:
# Transpose a matrix (swap rows and columns)
transposed = reshaped.T
print("Transposed (3,2):")
print(transposed)

Transposed (3,2):
[[1 4]
 [2 5]
 [3 6]]


## Section 9: Data Loading - Reading from Files
**Load data from CSV files using NumPy**

In [51]:
# Load data from CSV file
data = np.genfromtxt('../../CSV_File/zomato.csv', delimiter=',', dtype=str)
print("Data shape:", data.shape)
print("First 2 rows:")
print(data[:2])

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 952: character maps to <undefined>

## Section 10: Boolean Masking - Filtering Data
**Use conditions to filter and extract array elements**

In [ ]:
# Create array for boolean masking and apply filter conditions
mask_arr = np.array([1,2,3,4,5,6,7,8,9,10])
mask = (mask_arr > 3) & (mask_arr < 8)
filtered = mask_arr[mask]
print("Elements between 3 and 8:", filtered)

Elements between 3 and 8: [4 5 6 7]


In [ ]:
## Section 11: Additional NumPy Operations
**Advanced operations: sorting, searching, and more**

SyntaxError: invalid syntax (513285527.py, line 2)

In [ ]:
# Create unsorted array for sorting demonstration
sort_arr = np.array([3,1,4,1,5,9,2,6])
print("Original unsorted array:", sort_arr)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Sort array in ascending order and find indices where condition is true
sorted_arr = np.sort(sort_arr)
print("Sorted array:", sorted_arr)

# Find indices of elements greater than 4
indices = np.where(sort_arr > 4)
print("Indices where elements > 4:", indices)
print("Elements at those indices:", sort_arr[indices[0]])

Addition : [5 7 9]
Substraction : [-3 -3 -3]
Multiplication : [ 4 10 18]
Divition : [4.  2.5 2. ]


In [ ]:
# Concatenate multiple arrays
concat_result = np.concatenate([sort_arr, [10, 11, 12]])
print("Concatenated array:", concat_result)

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


# Statistical concept-Normalization


In [ ]:
Data = np.array([1,2,3,4])

# Mean
mean = np.mean(Data)
print("mean is ", mean)

# Median
median = np.median(Data)
print("Median is ", median)

# Standard deviation
std_dev = np.std(Data)
print("mean is ", std_dev)

# Variance
variance = np.var(Data)
print("Variance is ", variance)

mean is  2.5
Median is  2.5
mean is  1.118033988749895
Variance is  1.25


In [ ]:
# To have a mean of 0 and standard deviation of 1 
# Normalized Data 

Data = np.array([1,2,3,4])

mean = np.mean(Data)
std_dev = np.std(Data)

normilized_data = (Data - mean ) / std_dev
print("Normilized data :", normilized_data)

Normilized data : [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [59]:
# logical operation
Data = np.array([1,2,3,4,6])

Data[Data>5]

array([6])