**IMPORTING NUMPY**

In [162]:
import numpy as np 

IN PYTHON INDEXING STARTS AT 0

**1D ARRAY(ROW)**

In [163]:
a = np.array([1,2,3,4],dtype = 'int32')
print(a)

[1 2 3 4]


**2D ARRAY(ROW X COLUMN)**

In [164]:
b = np.array([[9.0,8.0],[6.0,8.0]])
print(b)

[[9. 8.]
 [6. 8.]]


**GET DIMENTION**

In [165]:
a.ndim, b.ndim

(1, 2)

**GET SHAPE**

In [166]:
a.shape, b.shape

((4,), (2, 2))

**GET TYPE**

In [167]:
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

**SIZE OF EACH ELEMENTS**

In [168]:
a.itemsize, b.itemsize

(4, 8)

**TOTAL SIZE = NUMBER OF ELEMENTS X SIZE OF EACH ELEMENT(IN BYTES)**

In [169]:
a.nbytes, b.nbytes

(16, 32)

**ACCESSING/CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS, ETC**

In [170]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


**GET A SPECIFIC ELEMENT [R, C]**

In [171]:
a[1,5]

np.int64(13)

**GET A SPECIFIC ROW**

In [172]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

**GET A SPECIFIC COLUMN**

In [173]:
a[:,2]

array([ 3, 10])

**[ROW/COLUMN, START_INDEX : END_INDEX : STEP_SIZE]**

In [174]:
a[0,1:6:2], a[0,1:-1:2]

(array([2, 4, 6]), array([2, 4, 6]))

**CHANGE ELEMENTS**

In [175]:
a[1,5] = 20
print(a)

a[:,2] = [1,1]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  1 11 12 20 14]]


**3D ARRAY (N_LAYER, LAYER_ROW, LAYER_COLUMN)**

In [176]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c), c.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(None, (2, 2, 3))

**GET SPECIFIC ELEMENT**

In [177]:
c[0,1,2], c[:,1,:]

(np.int64(6),
 array([[ 4,  5,  6],
        [10, 11, 12]]))

**REPLACE**

In [178]:
c[:,1,:] = [[4,4,4],[5,5,5]]
c

array([[[1, 2, 3],
        [4, 4, 4]],

       [[7, 8, 9],
        [5, 5, 5]]])

**INITIALIZING DIFFERENT TYPES OF ARRAYS**